# Generated by Django 4.1.3 on 2022-11-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_anime',
        ),
    ]
