# Generated by Django 4.1.5 on 2023-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='currently_watching',
        ),
        migrations.RemoveField(
            model_name='useranime',
            name='finished_anime',
        ),
        migrations.RemoveField(
            model_name='useranime',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='useranime',
            name='watching_status',
            field=models.CharField(choices=[('CURRENTLY_WATCHING', 'Currently watching'), ('WATCHLIST', 'Watchlist'), ('FINISHED_ANIME', 'Finished Anime')], default=None, max_length=20),
        ),
    ]
