# Generated by Django 4.1.5 on 2023-01-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_useranime_currently_watching_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
    ]
