# Generated by Django 4.1.5 on 2023-01-15 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='useranime',
            name='watching_status',
            field=models.CharField(choices=[('NOT_WATCHING', 'Not Watching'), ('CURRENTLY_WATCHING', 'Currently watching'), ('WATCHLIST', 'Watchlist'), ('FINISHED_ANIME', 'Finished Anime')], default='NOT_WATCHING', max_length=20),
        ),
    ]
