# Generated by Django 4.1.5 on 2023-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useranime_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_anime',
            field=models.ManyToManyField(to='users.useranime'),
        ),
    ]
