# Generated by Django 4.1.5 on 2023-01-18 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_user_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
