# Generated by Django 4.1.5 on 2023-02-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_remove_animeawards_anime_award_name_and_more'),
        ('users', '0011_uservotedanime_userprofile_user_voted_animes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_voted_animes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_voted_animes',
            field=models.ManyToManyField(blank=True, null=True, to='anime.animeawards'),
        ),
    ]
