# Generated by Django 4.1.7 on 2023-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userprofile_user_voted_animes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
