# Generated by Django 4.1.3 on 2022-12-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('award_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominated_for_award', models.BooleanField()),
                ('has_award', models.BooleanField()),
                ('anime_award_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime.awards')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255, null=True)),
                ('small_image_url', models.URLField(max_length=255, null=True)),
                ('large_image_url', models.URLField(max_length=255, null=True)),
                ('trailer_youtube_url', models.URLField(max_length=255, null=True)),
                ('episodes', models.IntegerField(null=True)),
                ('studio', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('aired_from', models.DateField(null=True)),
                ('aired_to', models.DateField(null=True)),
                ('summary', models.TextField()),
                ('anime_awards', models.ManyToManyField(to='anime.animeawards')),
                ('anime_genre', models.ManyToManyField(to='anime.genre')),
            ],
        ),
    ]
