# Generated by Django 4.1.2 on 2022-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=255)),
                ('episodes', models.IntegerField()),
                ('studio_name', models.CharField(max_length=255)),
                ('aired', models.BooleanField(null=True)),
                ('status', models.DateField()),
                ('season', models.IntegerField()),
                ('summary', models.TextField()),
                ('anime_genre', models.ManyToManyField(to='anime.genre')),
            ],
        ),
    ]
