# Generated by Django 4.1.3 on 2022-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='studio',
            new_name='anime_studio',
        ),
    ]
