# Generated by Django 4.1.3 on 2022-11-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_awards_animeawards_anime_anime_awards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='season',
            new_name='seasons',
        ),
    ]
