# Generated by Django 4.1.3 on 2022-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_anime_studio_anime_anime_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='media_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
