# Generated by Django 4.1.3 on 2022-11-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_rename_season_anime_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeawards',
            name='anime_award_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime.awards'),
        ),
    ]
