# Generated by Django 4.1.3 on 2022-12-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
