# Generated by Django 4.1.3 on 2022-11-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_animeawards_anime_award_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_awards',
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_awards',
            field=models.ManyToManyField(to='anime.animeawards'),
        ),
    ]
