# Generated by Django 4.1.5 on 2023-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awards',
            name='award_description',
        ),
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(null=True),
        ),
    ]
