# Generated by Django 4.1.5 on 2023-01-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_remove_awards_award_description_anime_mal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeawards',
            name='nominated_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='animeawards',
            name='received_date',
            field=models.DateField(null=True),
        ),
    ]
