# Generated by Django 4.1.5 on 2023-01-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_anime_number_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anime',
            name='number_rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio_name',
        ),
        migrations.RemoveField(
            model_name='awards',
            name='award_description',
        ),
        migrations.AddField(
            model_name='anime',
            name='aired_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='aired_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='image_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='large_image_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='media_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='small_image_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='trailer_youtube_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_studio',
            field=models.ManyToManyField(to='anime.studio'),
        ),
    ]
