# Generated by Django 4.1.5 on 2023-02-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_uservotedanime_userprofile_user_voted_animes'),
        ('anime', '0010_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeawards',
            name='anime_award_name',
        ),
        migrations.RemoveField(
            model_name='animeawards',
            name='has_award',
        ),
        migrations.RemoveField(
            model_name='animeawards',
            name='nominated_for_award',
        ),
        migrations.AddField(
            model_name='animeawards',
            name='allUsers',
            field=models.ManyToManyField(to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='animeawards',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AddField(
            model_name='animeawards',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.awards'),
        ),
        migrations.AddField(
            model_name='animeawards',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awards',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_awards',
            field=models.ManyToManyField(to='anime.awards'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
