# Generated by Django 4.1.5 on 2023-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_remove_animeawards_anime_award_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
