# Generated by Django 4.1.5 on 2023-02-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_awards_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllWinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.animeawards')),
            ],
        ),
    ]
