# Generated by Django 4.1.7 on 2023-02-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_allwinners'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='number_rating',
            field=models.IntegerField(null=True),
        ),
    ]
