# Generated by Django 4.1.5 on 2023-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_alter_anime_number_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(null=True)),
                ('character_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_characters',
            field=models.ManyToManyField(to='anime.character'),
        ),
    ]
