# Generated by Django 4.1.5 on 2023-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_anime_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='number_rating',
        ),
        migrations.AddField(
            model_name='anime',
            name='num_rated',
            field=models.IntegerField(default=0),
        ),
    ]
