# Generated by Django 4.1.3 on 2022-12-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_watching', models.BooleanField()),
                ('watchlist', models.BooleanField()),
                ('finished_anime', models.BooleanField()),
                ('rating', models.IntegerField(null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('user_anime', models.ManyToManyField(to='user.useranime')),
            ],
        ),
    ]
