# Generated by Django 4.1.2 on 2022-11-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_useranime_remove_ingredient_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='place',
            new_name='user_anime',
        ),
    ]
