# Generated by Django 4.1.2 on 2022-11-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_place_user_user_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='name',
        ),
    ]
