# Generated by Django 4.1.2 on 2022-11-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        ('user', '0004_remove_useranime_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
    ]
