# Generated by Django 4.1.3 on 2022-11-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useranime_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_anime',
        ),
        migrations.AddField(
            model_name='user',
            name='user_anime',
            field=models.ManyToManyField(to='user.useranime'),
        ),
    ]
