# Generated by Django 4.1.3 on 2022-11-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_user_anime_user_user_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='notes',
        ),
        migrations.AddField(
            model_name='useranime',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
    ]
