# Generated by Django 4.1.3 on 2022-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_user_anime_user_user_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='notes',
        ),
        migrations.AddField(
            model_name='useranime',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
