# Generated by Django 4.1.3 on 2022-11-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_useranime_notes_useranime_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
