# Generated by Django 4.1.3 on 2022-11-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_useranime_notes_useranime_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_anime',
        ),
        migrations.CreateModel(
            name='AllUserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_user_anime', models.ManyToManyField(to='user.useranime')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_anime',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.alluseranime'),
        ),
    ]
