# Generated by Django 4.1.3 on 2022-11-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_useranime_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranime',
            name='user_rating',
        ),
    ]
