# Generated by Django 4.1.3 on 2022-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_useranime_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranime',
            name='user_anime',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
