# Generated by Django 4.1.3 on 2022-11-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranime',
            name='watchlist',
            field=models.IntegerField(null=True),
        ),
    ]
