# Generated by Django 4.1.3 on 2022-11-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_useranime_user_anime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranime',
            old_name='user_anime',
            new_name='rating',
        ),
    ]
